### ISSUE TITLE
Update for Jellyfin 10.9.x

### ISSUE THREAD

**Issue by marvin8** [bonukai/jellyfin-plugin-mediatracker#6]
My Jellyfin version 10.9.1 shows the mediatracker plugin as "NotSupported"
Is there any easy way to up date this plugin to make it "Supported" again in Jellyfin 10.9.x ?

**Comment by SkalCore** [comment]
I have already asked here directly, but unfortunately I have not yet received an answer https://github.com/bonukai/MediaTracker/issues/615

**Comment by bonukai** [comment]
Plugin has been updated to Jellyfin 10.9.1

**Comment by marvin8** [comment]
Thanks for the update. It's installed ok, will report back after I have watched some episodes
