### ISSUE TITLE
Can't install the plugin on jellyfin

### ISSUE THREAD

**Issue by buave** [bonukai/jellyfin-plugin-mediatracker#8]
Hello,

I can't install the plugin on jellyfin.
I've added the repo, but when I click on the MediaTraker plugin the plugin doesn't load (it loads in a loop) and so I can't install it.

I've looked at the jellyfin logs, no errors. And my DNS doesn't block any requests 

Jellyfin version: 10.9.2

Thanks in advance

**Comment by bonukai** [comment]
This was caused by missing `changelog` property in the manifest file. Now updated, and it should load properly

**Comment by buave** [comment]
Nice, all good. Thanks
